const $=id=>document.getElementById(id);let kind='carousel',settings={},cache={},playing=true,elapsed=0,last=performance.now(),busy=false,ready=false,epoch=0,switchToken=0;
const motion=()=>$('scene').contentWindow.Motion;
function fit(){const wrap=document.querySelector('.wrap'),s=Math.min((wrap.clientWidth-20)/720,(wrap.clientHeight-20)/1280),h=document.querySelector('.holder');h.style.width=720*s+'px';h.style.height=1280*s+'px';$('scene').style.transform=`scale(${s})`;}
window.addEventListener('resize',fit);
function stale(){epoch++;$('result').hidden=true;}
function fields(){ $('duration').value=settings.duration;$('showText').checked=settings.showText;$('seek').max=settings.duration;$('carouselFields').hidden=kind!=='carousel';$('gradientFields').hidden=kind!=='gradient';
 if(kind==='gradient'){for(const k of ['title','subtitle','accent'])$(k).value=settings[k];}
 else {const host=$('carouselFields');host.replaceChildren();for(let i=0;i<3;i++){const slot=document.createElement('div');slot.className='image-slot';const img=document.createElement('img');img.src=settings.images[i];img.alt='卡片 '+(i+1);slot.append(img);const label=document.createElement('label');label.textContent='卡片 '+(i+1)+' · 更换图片';const file=document.createElement('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.id='image'+i;file.onchange=async()=>{const f=file.files[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>4000000){$('status').textContent='请选择4MB以内的PNG/JPEG/WebP。';return;}const token=switchToken;const fr=new FileReader();fr.onload=async()=>{if(token!==switchToken)return;try{const test=new Image();test.src=fr.result;await test.decode();settings.images[i]=fr.result;img.src=fr.result;await apply();$('status').textContent='卡片图片已更新。';}catch{$('status').textContent='图片无法读取。';}};fr.readAsDataURL(f);};label.append(file);slot.append(label);const text=document.createElement('input');text.id='title'+i;text.maxLength=40;text.value=settings.titles[i];text.placeholder='可选标题';text.oninput=()=>{settings.titles[i]=text.value;apply();};slot.append(text);host.append(slot);}}
}
async function apply(){if(!ready)return;stale();await motion().setConfig(settings);cache[kind]=structuredClone(settings);elapsed=Math.min(elapsed,settings.duration-.001);$('seek').max=settings.duration;motion().renderAt(elapsed);}
async function switchKind(next,override){const token=++switchToken;ready=false;if(Object.keys(settings).length)cache[kind]=structuredClone(settings);kind=next;$('kind').value=kind;stale();elapsed=0;await new Promise((resolve,reject)=>{$('scene').onload=resolve;$('scene').onerror=reject;$('scene').src='/advanced/animations/'+kind+'/index.html';});if(token!==switchToken)return;settings={...motion().defaults(),...(override||cache[kind]||{})};await motion().setConfig(settings);ready=true;fields();fit();motion().renderAt(0);$('status').textContent=kind==='carousel'?'中间卡片放大亮起，上下卡片缩小变灰。':'光流与节点聚合成环，再收成四角星与标题卡。';}
$('kind').onchange=()=>switchKind($('kind').value);$('duration').onchange=()=>{settings.duration=Math.max(6,Math.min(16,Number($('duration').value)||9));$('duration').value=settings.duration;apply();};$('showText').onchange=()=>{settings.showText=$('showText').checked;apply();};for(const k of ['title','subtitle','accent'])$(k).oninput=()=>{settings[k]=$(k).value;apply();};
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'暂停':'播放';};$('seek').oninput=()=>{playing=false;$('play').textContent='播放';elapsed=Number($('seek').value);if(ready)motion().renderAt(elapsed);};
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
$('save').onclick=()=>download(kind+'-parameters.json',JSON.stringify({kind,settings},null,2));$('loadButton').onclick=()=>$('load').click();$('load').onchange=async()=>{try{const f=$('load').files[0];if(!f)return;const c=JSON.parse(await f.text());const r=await fetch('/api/advanced/studies/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});const out=await r.json();if(!r.ok)throw Error(out.error);await switchKind(out.kind,out.settings);}catch(e){$('status').textContent='读取失败：'+e.message;}};
$('export').onclick=async()=>{if(busy||!ready)return;busy=true;$('export').disabled=true;const token=epoch;try{let r=await fetch('/api/advanced/studies/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,settings})});let job=await r.json();if(!r.ok)throw Error(job.error);while(!['done','failed'].includes(job.status)){$('status').textContent=`正在导出 ${job.frames||0}/${job.total} 帧`;await new Promise(r=>setTimeout(r,800));r=await fetch('/api/advanced/jobs/'+job.id);job=await r.json();if(!r.ok)throw Error(job.error);}if(job.status==='failed')throw Error(job.error);if(token===epoch){$('result').href=job.url;$('result').download=kind+'.mp4';$('result').hidden=false;$('status').textContent=`已导出 ${job.duration}秒 · 720×1280 · 30fps · 无声。`;}else $('status').textContent='旧参数的视频已完成；当前参数有变动，请重新导出。';}catch(e){$('status').textContent='导出未完成：'+e.message;}finally{busy=false;$('export').disabled=false;}};
requestAnimationFrame(function tick(now){if(ready&&playing&&!busy){elapsed=(elapsed+(now-last)/1000)%settings.duration;motion().renderAt(elapsed);$('seek').value=elapsed;$('time').textContent=elapsed.toFixed(2)+'s';}last=now;requestAnimationFrame(tick);});
window.StudyStudio={ready:()=>ready,isBusy:()=>busy,getConfig:()=>({kind,settings:structuredClone(settings)}),setConfig:async c=>switchKind(c.kind,c.settings),pause:()=>{playing=false;$('play').textContent='播放';}};switchKind(new URLSearchParams(location.search).get('kind')==='gradient'?'gradient':kind);
